/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROTOTIPOS;

/**
 *
 * @author Andres Villamil
 */
public class wireframe extends javax.swing.JFrame {

    /**
     * Creates new form wireframe
     */
    public wireframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RecuerdameCheckBox = new javax.swing.JCheckBox();
        IniciarSesionButton = new javax.swing.JButton();
        OlvideContraseñaButton = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        txtNombre3 = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();
        RegresarButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 51));
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/logo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 70, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 0, 78));
        jLabel2.setText("Usuario");
        jLabel2.setMaximumSize(new java.awt.Dimension(40, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, 20));

        jTextUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jTextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 4, 54));
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        RecuerdameCheckBox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RecuerdameCheckBox.setForeground(new java.awt.Color(239, 0, 79));
        RecuerdameCheckBox.setText("Recuerdame");
        RecuerdameCheckBox.setBorder(null);
        RecuerdameCheckBox.setContentAreaFilled(false);
        getContentPane().add(RecuerdameCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        IniciarSesionButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IniciarSesionButton.setForeground(new java.awt.Color(207, 163, 0));
        IniciarSesionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/iniciar-sesion.png"))); // NOI18N
        IniciarSesionButton.setText("Iniciar sesion");
        IniciarSesionButton.setBorder(null);
        IniciarSesionButton.setBorderPainted(false);
        IniciarSesionButton.setContentAreaFilled(false);
        IniciarSesionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IniciarSesionButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/login.png"))); // NOI18N
        IniciarSesionButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/login.png"))); // NOI18N
        IniciarSesionButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        IniciarSesionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IniciarSesionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarSesionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IniciarSesionButtonMouseExited(evt);
            }
        });
        IniciarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarSesionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 90, 80));

        OlvideContraseñaButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        OlvideContraseñaButton.setForeground(new java.awt.Color(245, 1, 53));
        OlvideContraseñaButton.setText("Olvidé la contraseña");
        OlvideContraseñaButton.setContentAreaFilled(false);
        OlvideContraseñaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OlvideContraseñaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OlvideContraseñaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OlvideContraseñaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, 20));

        RegresarButton.setBackground(new java.awt.Color(207, 163, 0));
        RegresarButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegresarButton.setForeground(new java.awt.Color(207, 163, 0));
        RegresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/back 38.png"))); // NOI18N
        RegresarButton.setText("Regresar");
        RegresarButton.setBorder(null);
        RegresarButton.setBorderPainted(false);
        RegresarButton.setContentAreaFilled(false);
        RegresarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegresarButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/back 48.png"))); // NOI18N
        RegresarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/back 48.png"))); // NOI18N
        RegresarButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RegresarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegresarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarButtonMouseEntered(evt);
            }
        });
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 520));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/logo.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 70, 80));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 200, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(207, 163, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/LOGIN2.png"))); // NOI18N
        jButton1.setText("login");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 70, 70));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(207, 163, 0));
        jButton2.setText("REGISTAR");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 110, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/logo.png"))); // NOI18N
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 70, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/fondo.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 250, 210));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 0, 78));
        jLabel9.setText("NOMBRE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 60, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 0, 78));
        jLabel10.setText("APELLIDO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 70, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 0, 78));
        jLabel11.setText("USUARIO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 250, 0));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 0, 78));
        jLabel12.setText("CONTRASEÑA");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 110, 20));

        txtNombre1.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre1.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 110, 20));

        txtNombre2.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre2.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 110, 20));

        txtNombre3.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre3.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 110, 20));

        guardarButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        guardarButton.setForeground(new java.awt.Color(207, 163, 0));
        guardarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/guardar.png"))); // NOI18N
        guardarButton.setText("GUARDAR");
        guardarButton.setBorderPainted(false);
        guardarButton.setContentAreaFilled(false);
        guardarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        guardarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarButtonMouseExited(evt);
            }
        });
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(guardarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 100, 80));

        RegresarButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RegresarButton1.setForeground(new java.awt.Color(207, 163, 0));
        RegresarButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/back 38.png"))); // NOI18N
        RegresarButton1.setText("REGRESAR");
        RegresarButton1.setBorderPainted(false);
        RegresarButton1.setContentAreaFilled(false);
        RegresarButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegresarButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RegresarButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegresarButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarButton1MouseExited(evt);
            }
        });
        RegresarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(RegresarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/fondo.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 250, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsuarioActionPerformed

    private void OlvideContraseñaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OlvideContraseñaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OlvideContraseñaButtonActionPerformed

    private void IniciarSesionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionButtonMouseEntered
        IniciarSesionButton.setText("Iniciar sesion");
    }//GEN-LAST:event_IniciarSesionButtonMouseEntered

    private void IniciarSesionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionButtonMouseExited
        IniciarSesionButton.setText("             ");
    }//GEN-LAST:event_IniciarSesionButtonMouseExited

    private void IniciarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarSesionButtonActionPerformed

    private void RegresarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarButtonMouseEntered
        
    }//GEN-LAST:event_RegresarButtonMouseEntered

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        

    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void txtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2ActionPerformed

    private void txtNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre3ActionPerformed

    private void guardarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtonMouseEntered
       
    }//GEN-LAST:event_guardarButtonMouseEntered

    private void guardarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtonMouseExited
        
    }//GEN-LAST:event_guardarButtonMouseExited

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed

        
            
        
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void RegresarButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarButton1MouseEntered
        
    }//GEN-LAST:event_RegresarButton1MouseEntered

    private void RegresarButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarButton1MouseExited
        
    }//GEN-LAST:event_RegresarButton1MouseExited

    private void RegresarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButton1ActionPerformed
       
    }//GEN-LAST:event_RegresarButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wireframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wireframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wireframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wireframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wireframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarSesionButton;
    private javax.swing.JButton OlvideContraseñaButton;
    private javax.swing.JCheckBox RecuerdameCheckBox;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JButton RegresarButton1;
    private javax.swing.JButton guardarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtNombre3;
    // End of variables declaration//GEN-END:variables
}
