
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andres Villamil
 */
public class tarea extends javax.swing.JFrame {

    /**
     * Creates new form tarea
     */
    public tarea() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OlvideContraseñaButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RecuerdameCheckBox = new javax.swing.JCheckBox();
        RegresarButton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        IniciarSesionButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OlvideContraseñaButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        OlvideContraseñaButton.setForeground(new java.awt.Color(245, 1, 53));
        OlvideContraseñaButton.setText("Olvidé la contraseña");
        OlvideContraseñaButton.setContentAreaFilled(false);
        OlvideContraseñaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OlvideContraseñaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OlvideContraseñaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OlvideContraseñaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 0, 78));
        jLabel2.setText("Usuario");
        jLabel2.setMaximumSize(new java.awt.Dimension(40, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, 20));

        jTextUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jTextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 4, 54));
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        RecuerdameCheckBox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RecuerdameCheckBox.setForeground(new java.awt.Color(239, 0, 79));
        RecuerdameCheckBox.setText("Recuerdame");
        RecuerdameCheckBox.setBorder(null);
        RecuerdameCheckBox.setContentAreaFilled(false);
        getContentPane().add(RecuerdameCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        RegresarButton.setBackground(new java.awt.Color(207, 163, 0));
        RegresarButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegresarButton.setForeground(new java.awt.Color(207, 163, 0));
        RegresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/back 38.png"))); // NOI18N
        RegresarButton.setText("Regresar");
        RegresarButton.setBorder(null);
        RegresarButton.setBorderPainted(false);
        RegresarButton.setContentAreaFilled(false);
        RegresarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegresarButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/back 48.png"))); // NOI18N
        RegresarButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/back 48.png"))); // NOI18N
        RegresarButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RegresarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegresarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarButtonMouseEntered(evt);
            }
        });
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 60, 60));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 200, 30));

        IniciarSesionButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IniciarSesionButton.setForeground(new java.awt.Color(207, 163, 0));
        IniciarSesionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/iniciar-sesion.png"))); // NOI18N
        IniciarSesionButton.setText("Iniciar sesion");
        IniciarSesionButton.setBorder(null);
        IniciarSesionButton.setBorderPainted(false);
        IniciarSesionButton.setContentAreaFilled(false);
        IniciarSesionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IniciarSesionButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/login.png"))); // NOI18N
        IniciarSesionButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/login.png"))); // NOI18N
        IniciarSesionButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        IniciarSesionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IniciarSesionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarSesionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IniciarSesionButtonMouseExited(evt);
            }
        });
        IniciarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarSesionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 90, 80));

        jLabel4.setBackground(new java.awt.Color(255, 255, 51));
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/logo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 70, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OlvideContraseñaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OlvideContraseñaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OlvideContraseñaButtonActionPerformed

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        Menu ventana = new Menu();
        ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void jTextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsuarioActionPerformed

    private void IniciarSesionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionButtonMouseEntered
        IniciarSesionButton.setText("Iniciar sesion");
    }//GEN-LAST:event_IniciarSesionButtonMouseEntered

    private void IniciarSesionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionButtonMouseExited
        IniciarSesionButton.setText("             ");
    }//GEN-LAST:event_IniciarSesionButtonMouseExited

    private void IniciarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarSesionButtonActionPerformed

    private void RegresarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarButtonMouseEntered
        RegresarButton.setText("Regresar");
    }//GEN-LAST:event_RegresarButtonMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        RegresarButton.setText("  ");
    }//GEN-LAST:event_formMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarSesionButton;
    private javax.swing.JButton OlvideContraseñaButton;
    private javax.swing.JCheckBox RecuerdameCheckBox;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
